CREATE TABLE [dbo].[BRAND]
(
	[IDBRAND] INT NOT NULL PRIMARY KEY, 
    [BC_CODE] VARCHAR(10) NULL, 
    [CODICE] VARCHAR(10) NOT NULL, 
    [DESCRIZIONE] VARCHAR(25) NULL, 
    [CANCELLATO] BIT NOT NULL, 
    [DATAMODIFICA] DATETIME NOT NULL, 
    [UTENTEMODIFICA] VARCHAR(50) NOT NULL
)

GO

CREATE UNIQUE INDEX [IX_BRAND_CODICE] ON [dbo].[BRAND] ([CODICE])
